### ISSUE TITLE
Non Functional

### ISSUE THREAD

**Issue by KevinRichard-GM** [ironmonk88/always-hp#2] opened 2021-01-12 01:21 UTC
Only button on the bar that works is the skull (only applies the dead image, does not set HP to 0). Damage, Heal and Full Heal do nothing.

**Comment by ironmonk88** [comment] 2021-01-12 01:28
What game system are you using?

**Comment by KevinRichard-GM** [comment] 2021-01-12 01:29
Pathfinder 2

**Comment by KevinRichard-GM** [comment] 2021-01-12 01:34
Name shows in the window along with the current hit points in brackets so it appears to be hooked to the correct field for HP.

**Comment by ironmonk88** [comment] 2021-01-12 01:44
I think I figured out the issue.  Might take me a bit to fix it though.

**Comment by Nargath** [comment] 2021-01-12 05:18
This is also the same case for Pathfinder 1.
The only functional button is triggering the Dead state

**Comment by JJBocanegra** [comment] 2021-01-12 15:07
I can't make it work in D&D 5e either.

**Comment by ironmonk88** [comment] 2021-01-12 18:00
JJBocanegra, what version are you using?  What problem are you having and are there any errors in the debug console?

**Comment by ironmonk88** [comment] 2021-01-12 18:01
Added support for Pathfinder 2.  It should work for Pathfinder 1 as well, but I've limited it until I can confirm it's working.

**Comment by JJBocanegra** [comment] 2021-01-14 10:03
@ironmonk88 this is the problem I'm having, with the latest version (v1.0.9 at the moment) and with no errors on console.

![always-hp](https://user-images.githubusercontent.com/5797636/104576051-02432e00-5658-11eb-8de3-d20c8751854f.gif)

**Comment by JLtheking2** [comment] 2021-01-14 17:25
The reason why this is happening to you guys in the thread is because the box does not have a number in it when you press the damage or heal numbers. When the field is empty when you press the buttons, it deducts or adds NaN from the selected token's HP. Int +/- NaN = NaN. This results on the token you selected dropping to NaN hit points.

To solve this, I suggest having the buttons treat the empty field as '1', subtracting or increasing the target by 1 hit point each time the button is pressed without field filled.

**Comment by ironmonk88** [comment] 2021-01-14 17:33
That's exactly the approach I took.  new version has been released and is available for update.

**Comment by ironmonk88** [comment] 2021-01-14 17:34
Also closing this ticket as the original issue has been solved.

**Closed by ironmonk88** 2021-01-14 17:34 UTC

**Comment by ironmonk88** [comment] 2021-01-14 17:35
Also really appreciate the video showing the issue.  But... how did an Ape get into the Redbrand Hideout!!  That's the real question.  :-)

**Comment by JJBocanegra** [comment] 2021-01-14 19:43
It's the number of hitpoints supposed to be empty all the time? It's the only issue that I see right now 🤔

P.S.: What an eye you have to have recognized the map haha

**Comment by ironmonk88** [comment] 2021-01-14 19:52
The Textbox is supposed to be empty (until you fill it).  It's not like the HP field you get when you click on the token.  And really only applies to the up and down arrows.  So if you typed 5 into the textbox and hit the down arrow, it would take 5 HP away.  Same with the heal button, just in the other direction.  If you want to see what the current HP of the actor is it appears in the square brackets after the name.  But the Always HP textbox is only meant for how much you want to change the HP by, not to show how much the HP is.
